services:
  backend:
    build: ./backend
    image: muzero-backend
    expose:
      - "8080"
    volumes:
      - ./backend:/app # Sync the backend folder with the container

  frontend:
    build: ./frontend
    image: muzero-frontend
    ports:
      - "9135:80"
    depends_on:
      - backend
