_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 16
                - 23
                - 35
                - 55
                - 61
                - 62
            "4": 3.12.7
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
action_space_size:
    value: 2
epochs:
    value: 1
hidden_layer_size:
    value: 188
learning_rate:
    value: 0.0277
learning_rate_decay:
    value: 0.995
learning_rate_decay_steps:
    value: 1000
momentum:
    value: 0.9
num_unroll_steps:
    value: 500
observation_space_size:
    value: 4
td_steps:
    value: 50
training_episodes:
    value: 100000
weight_decay:
    value: 0.0001
